[tool.poetry]
name = "mini-vpn"
version = "0.1.0"
description = ""
authors = ["ice1187"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
